version: '3.8'

services:
  # Central Server (CS + SSM)
  central-server:
    image: niis/xroad-central-server:7.6.1
    container_name: xroad-central-server
    ports:
      - "4000:4000"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - central-server-data:/var/lib/xroad
      - ./config/central-server/xroad.properties:/etc/xroad/conf.d/local.ini
    environment:
      - XROAD_TOKEN_PIN=1234
      - XROAD_ADMIN_USER=xroad
      - XROAD_ADMIN_PASSWORD=xroad
    networks:
      - xroad-network

  # Security Server (SS)
  security-server:
    image: niis/xroad-security-server:7.6.1
    container_name: xroad-security-server
    ports:
      - "4001:4000"
      - "8081:8080"
      - "8444:8443"
    volumes:
      - security-server-data:/var/lib/xroad
      - ./config/security-server/xroad.properties:/etc/xroad/conf.d/local.ini
      - ./config/security-server/conf.d:/etc/xroad/conf.d
    environment:
      - XROAD_TOKEN_PIN=1234
      - XROAD_ADMIN_USER=xroad
      - XROAD_ADMIN_PASSWORD=xroad
      - XROAD_CENTRAL_SERVER_ADDRESS=central-server
    networks:
      - xroad-network
    depends_on:
      - central-server

  # Simple CA
  simple-ca:
    image: nginx:alpine
    container_name: xroad-ca
    volumes:
      - ./ca:/usr/share/nginx/html
      - ./config/ca/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"
    networks:
      - xroad-network

  # HTTP URL Checker (HURL)
  hurl:
    image: nginx:alpine
    container_name: xroad-hurl
    volumes:
      - ./hurl:/usr/share/nginx/html
      - ./config/hurl/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9999:80"
    networks:
      - xroad-network

networks:
  xroad-network:
    driver: bridge

volumes:
  central-server-data:
  security-server-data: